import pandas as pd

def generate_markdown_report(ticker, market_data, financials, results, epv_value, equity_epv, repro_value, franchise_value, ai_reasoning):
    """
    Generates a Markdown report for the SaaS EPV Analysis.
    """

    company_name = market_data.get('company_name', ticker)
    price = market_data.get('price', 0)
    mcap_billions = market_data.get('market_cap', 0) / 1e9

    # Calculate Per Share Metrics
    shares = financials.get('shares_outstanding', 1)
    epv_per_share = equity_epv / shares
    upside = (epv_per_share - price) / price * 100 if price else 0

    # Format currency helpers
    def fmt_b(val): return f"${val/1e9:.1f}B"
    def fmt_p(val): return f"{val:.1f}%"

    report = f"""# SaaS EPV Analysis Report: {company_name} ({ticker})
**Date:** {pd.Timestamp.now().strftime('%Y-%m-%d')}

## Executive Summary
*   **Current Price:** ${price:.2f}
*   **Target Price (EPV):** ${epv_per_share:.2f}
*   **Upside/Downside:** {upside:+.1f}%
*   **Recommendation:** {"Undervalued" if upside > 0 else "Overvalued"}

## Valuation Metrics
| Metric | Value | Description |
| :--- | :--- | :--- |
| **Market Cap** | {fmt_b(market_data.get('market_cap', 0))} | Current Market Value |
| **Firm EPV** | {fmt_b(epv_value)} | Operations Value (Zero Growth) |
| **Net Cash** | {fmt_b(financials.get('cash', 0) - financials.get('debt', 0))} | Cash - Debt |
| **Equity EPV** | {fmt_b(equity_epv)} | Intrinsic Equity Value |

## Financial Analysis (Normalized)
The Greenwald EPV method separates maintenance spending from growth investments to reveal true earnings power.

*   **Reported EBIT:** {fmt_b(financials.get('ebit', 0))}
*   **Normalized EBIT:** {fmt_b(results['normalized_ebit'])} (Adjusted for Growth Spend)
*   **NOPAT:** {fmt_b(results['nopat'])} (Net Operating Profit After Tax)

## Moat Analysis
*   **Reproduction Value:** {fmt_b(repro_value)} (Cost to replicate assets)
*   **Franchise Value:** {fmt_b(franchise_value)} (Value of competitive advantage)
*   **Moat Status:** {"Wide Moat" if franchise_value > 0 else "No Moat"} ({fmt_p(franchise_value/epv_value*100 if epv_value else 0)} of Firm EPV)

## AI Growth Expenditure Analysis
**AI Reasoning:**
> {ai_reasoning}

---
*Generated by SaaS EPV Analyzer*
"""
    return report
